# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoReactNavigation' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoReactNavigation

  

  platform :ios, '9.0'

  target 'DemoReactNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoReactNavigation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoReactNavigation-tvOS

  target 'DemoReactNavigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
